-- ====================================================================
-- 自动生成配置 :
-- ====================================================================

--[[
字段结构说明:

  id - 物品ID (int)
  name - 名称 (string)
  description - 描述 (string)
  type - 类型 (int)
  sub_type - 子类型 (int)
  quality - 品质 (int)
  level - 等级 (int)
  auto_use - 自动使用 (bool)
  discard - 是否可丢弃 (bool)
  max_stack - 最大堆叠 (long)
  sell_price - 出售价格 (int)
  buy_price - 购买价格 (int)
  gas_effects - 效果id(对应能力表效果id) ((array#sep=,),int)
  damage - 伤害 (double)
  attack_speed - 攻击速度 (double)
  armor - 护甲值 (int)
  slot - 装备槽位 (int)
--]]

local M = {
    [1] = {
        id = 1,
        name = "金币",
        description = "金币",
        type = 0,
        sub_type = 0,
        quality = 6,
        level = 0,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 0,
        buy_price = 0,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [2] = {
        id = 2,
        name = "经验",
        description = "经验",
        type = 0,
        sub_type = 0,
        quality = 1,
        level = 0,
        auto_use = true,
        discard = false,
        max_stack = 0,
        sell_price = 0,
        buy_price = 0,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [1001] = {
        id = 1001,
        name = "铁剑",
        description = "一把普通的铁制长剑",
        type = 1,
        sub_type = 0,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 30,
        buy_price = 90,
        gas_effects = {},
        damage = 15.0,
        attack_speed = 1.0,
        armor = 0,
        slot = 0,
    },

    [1002] = {
        id = 1002,
        name = "钢剑",
        description = "优质钢材锻造的长剑，锋利而坚固",
        type = 1,
        sub_type = 0,
        quality = 3,
        level = 5,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 125,
        buy_price = 375,
        gas_effects = {},
        damage = 25.0,
        attack_speed = 1.2,
        armor = 0,
        slot = 0,
    },

    [1003] = {
        id = 1003,
        name = "传奇之刃",
        description = "传说中的神兵利器，散发着耀眼的光芒",
        type = 1,
        sub_type = 0,
        quality = 6,
        level = 20,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 3000,
        buy_price = 9000,
        gas_effects = {},
        damage = 100.0,
        attack_speed = 1.5,
        armor = 0,
        slot = 0,
    },

    [1004] = {
        id = 1004,
        name = "战斧",
        description = "沉重的双手战斧，威力惊人",
        type = 1,
        sub_type = 0,
        quality = 4,
        level = 10,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 450,
        buy_price = 1350,
        gas_effects = {},
        damage = 45.0,
        attack_speed = 0.8,
        armor = 0,
        slot = 0,
    },

    [2001] = {
        id = 2001,
        name = "皮甲",
        description = "简单的皮革护甲",
        type = 2,
        sub_type = 0,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 15,
        buy_price = 45,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 10,
        slot = 2,
    },

    [2002] = {
        id = 2002,
        name = "铁头盔",
        description = "铁制头盔，提供基础防护",
        type = 2,
        sub_type = 0,
        quality = 2,
        level = 3,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 36,
        buy_price = 108,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 8,
        slot = 1,
    },

    [2003] = {
        id = 2003,
        name = "钢板甲",
        description = "重型钢制板甲，防御力强大",
        type = 2,
        sub_type = 0,
        quality = 4,
        level = 8,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 420,
        buy_price = 1260,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 35,
        slot = 2,
    },

    [2004] = {
        id = 2004,
        name = "铁护腿",
        description = "铁制护腿，保护双腿",
        type = 2,
        sub_type = 0,
        quality = 3,
        level = 4,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 72,
        buy_price = 216,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 12,
        slot = 3,
    },

    [2005] = {
        id = 2005,
        name = "皮手套",
        description = "柔软的皮革手套",
        type = 2,
        sub_type = 0,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 0,
        sell_price = 8,
        buy_price = 24,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 5,
        slot = 4,
    },

    [3001] = {
        id = 3001,
        name = "生命药水",
        description = "恢复50点生命值",
        type = 3,
        sub_type = 7,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 25,
        buy_price = 50,
        gas_effects = { 6, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [3002] = {
        id = 3002,
        name = "魔法药水",
        description = "恢复30点魔法值",
        type = 3,
        sub_type = 8,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 15,
        buy_price = 30,
        gas_effects = { 7, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [3003] = {
        id = 3003,
        name = "超级生命药水",
        description = "恢复150点生命值",
        type = 3,
        sub_type = 7,
        quality = 4,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 75,
        buy_price = 150,
        gas_effects = { 8, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [3004] = {
        id = 3004,
        name = "超级魔法药水",
        description = "恢复100点魔法值",
        type = 3,
        sub_type = 8,
        quality = 4,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 50,
        buy_price = 100,
        gas_effects = { 9, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [3005] = {
        id = 3005,
        name = "力量药水",
        description = "临时提升30点力量,持续60秒",
        type = 3,
        sub_type = 9,
        quality = 3,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 40,
        buy_price = 80,
        gas_effects = { 10, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [3006] = {
        id = 3006,
        name = "敏捷药水",
        description = "临时提升25点敏捷,持续60秒",
        type = 3,
        sub_type = 10,
        quality = 3,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 40,
        buy_price = 80,
        gas_effects = { 11, },
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [4001] = {
        id = 4001,
        name = "铁矿石",
        description = "基础的铁矿石，可用于锻造",
        type = 4,
        sub_type = 1,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 200,
        sell_price = 1,
        buy_price = 5,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [4002] = {
        id = 4002,
        name = "魔法草药",
        description = "蕴含魔力的草药，可用于炼金",
        type = 4,
        sub_type = 2,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 200,
        sell_price = 2,
        buy_price = 8,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [4003] = {
        id = 4003,
        name = "兽皮",
        description = "野兽的皮毛，可用于制作护甲",
        type = 4,
        sub_type = 3,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 200,
        sell_price = 1,
        buy_price = 4,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [4004] = {
        id = 4004,
        name = "布匹",
        description = "普通的布料",
        type = 4,
        sub_type = 4,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 200,
        sell_price = 1,
        buy_price = 3,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [4005] = {
        id = 4005,
        name = "秘银矿",
        description = "稀有的秘银矿石，价值不菲",
        type = 4,
        sub_type = 1,
        quality = 4,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 100,
        sell_price = 20,
        buy_price = 100,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [5001] = {
        id = 5001,
        name = "哥布林的耳朵",
        description = "任务物品：击败哥布林的证明",
        type = 5,
        sub_type = 0,
        quality = 2,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 99,
        sell_price = 0,
        buy_price = 0,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

    [5002] = {
        id = 5002,
        name = "古老的卷轴",
        description = "任务物品：记载着古老魔法的卷轴",
        type = 5,
        sub_type = 0,
        quality = 4,
        level = 1,
        auto_use = false,
        discard = false,
        max_stack = 1,
        sell_price = 0,
        buy_price = 0,
        gas_effects = {},
        damage = 0.0,
        attack_speed = 0.0,
        armor = 0,
        slot = 0,
    },

}

LOG_INFO(" 加载完成")

return M
